### ISSUE TITLE
I try to run FFmpeg command but its given me FFmpeg process exited with rc 1. can you help me out

### ISSUE THREAD

**Issue by prince262** [tanersener/react-native-ffmpeg-test#12]

**Comment by ahmad-tech** [comment]
Need help on this.

**Comment by tanersener** [comment]
rc = 1 means command failed. You need to look at the console output to understand what went wrong.

**Comment by tanersener** [comment]
This project will be retired. Please consider switching to [FFmpegKit](https://github.com/tanersener/ffmpeg-kit) and [FFmpegKitTest](https://github.com/tanersener/ffmpeg-kit-test).
