### ISSUE TITLE
No such file or directory on Android

### ISSUE THREAD

**Issue by BILLXZY1215** [tanersener/react-native-ffmpeg-test#20]
I tried to process a video on my phone:

![WechatIMG650](https://user-images.githubusercontent.com/61944458/131776581-ac47b753-0278-4bd4-9a1a-0f8efbe6392f.jpeg)

But I've got the error that cannot find this video: 

![WechatIMG651](https://user-images.githubusercontent.com/61944458/131776596-22eeb00a-5f88-4b53-bf95-7c01fd9db4d4.jpeg)

I'm not sure what's the correct folder URI, using the FFmpeg command in this app.
Can you help me with this? Thanks a lot.

**Comment by tanersener** [comment]
I don't know how you're getting that path. Please remember the following tip from the README.

`react-native-ffmpeg uses file system paths, it does not know what an assets folder or a project folder is. So you can't use resources on those folders directly, you need to provide full paths of those resources.`

**Comment by tanersener** [comment]
This project will be retired. Please consider switching to [FFmpegKit](https://github.com/tanersener/ffmpeg-kit) and [FFmpegKitTest](https://github.com/tanersener/ffmpeg-kit-test).
