### ISSUE TITLE
/ReactNativeFFmpegTest.app/colosseum.jpg: No such file or directory

### ISSUE THREAD

**Issue by idoor88** [tanersener/react-native-ffmpeg-test#4]
I got the app build and installed on my iphone device, it works when I use -version command, but when I switched to VIDEO tab and tap on CREATE button, it showed a message saying:

/var/containers/Bundle/Application/DF534C28-4412-4F59-AB33-9B486C4DAB86/ReactNativeFFmpegTest.app/colosseum.jpg: No such file or directory.

also in my console log, I saw the jpg files saved:
Saved resource colosseum.jpg to /var/containers/Bundle/Application/DF534C28-4412-4F59-AB33-9B486C4DAB86/ReactNativeFFmpegTest.app/colosseum.jpg
Main.js:285 Saved resource pyramid.jpg to /var/containers/Bundle/Application/DF534C28-4412-4F59-AB33-9B486C4DAB86/ReactNativeFFmpegTest.app/pyramid.jpg
Main.js:288 Saved resource tajmahal.jpg to /var/containers/Bundle/Application/DF534C28-4412-4F59-AB33-9B486C4DAB86/ReactNativeFFmpegTest.app/tajmahal.jpg

**Comment by tanersener** [comment]
Apparently images under the `Resources` folder are not found in the expected app bundle path. Can you verify that they are included in the application bundle?
